spring.application.name=avis

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:mem:avis
spring.datasource.driver-class-name=org.h2.Driver

management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=beans,health,env,configprops
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.health.group.custom.show-components=always
management.endpoint.health.group.custom.show-details=always
management.endpoint.env.show-values=always
management.endpoint.configprops.show-values=always

spring.data.rest.detection-strategy=annotated
springdoc.swagger-ui.try-it-out-enabled=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB

spring.profiles.active=dev

nom-dossier-images=src/main/resources/static/images

logo-dev-token=pk_IbzwLqxqTM2e8h2KSQME_g